### ISSUE TITLE
Can I stream youtube audio to an html audio tag using this?

### ISSUE THREAD

**Issue by AhsanSarwar45** [Luuk-Dev/YT-Stream#11]
Given a youtube video id, I am trying to stream (without downloading the entire audio beforehand) youtube audio to an html audio tag. Can this library be used for such a purpose? Maybe by giving the download url directly to the audio tag? If no, do you have any pointers on how it can be done? Any help would be greatly appreciated. 

Also, was wondering if it has ffmpeg dependency?

**Comment by Luuk-Dev** [comment]
It is not possible to use the download url of the YouTube video as this url IP bonded and as the server makes the request and not the client, the IP which it's bonded to, is the IP of the server and not the client, which makes it not possible for the client to access this url. What is possible though, is to use the `stream` function on the server side on a certain endpoint and use the `pipe` function to directly pass the data of the stream to the client, so you can use that endpoint to play the audio on the client side. Here is a small example of how you can do this:
```js
const http = require('http');
const ytstream = require('yt-stream');
const fs = require('fs');
const path = require('path');
const { URLSearchParams } = require('url');

function readFolder(arr){
	let res = [];
	for(var i = 0; i < arr.length; i++){
		let folderName = arr[i];
		let folderInfo = fs.readdirSync(path.join(__dirname, folderName));
		for(var z = 0; z < folderInfo.length; z++){
			let fileName = path.join(folderName, folderInfo[z]);
			let fileInfo = fs.statSync(path.join(__dirname, fileName));
			if(fileInfo.isFile()){
				res.push(fileName);
			} else if(fileInfo.isDirectory()){
				res.push(...readFolder([fileName]));
			}
		}
		return res;
	}
}

let pages = readFolder(['public_html']).map(f => f.split("public_html").slice(1).join("public_html"));

const server = http.createServer((req, res) => {
	let seperate = req.url.split("?");
	let url = seperate[0];
	if(pages.indexOf(url) >= 0){
		let fileContent = fs.readFileSync(path.join(__dirname, 'public_html', url));
		res.end(fileContent);
		return;
	} else if(pages.indexOf(url + "index.html") >=  0){
		let fileContent = fs.readFileSync(path.join(__dirname, 'public_html', url, "index.html"));
		res.end(fileContent);
		return;
	}
	let paramsArr = seperate.slice(1).join("?").split("&");
	let params = {};
	for(var i = 0; i < paramsArr.length; i++){
		let param = paramsArr[i];
		let splitParam = param.split("=");
		params[splitParam[0]] = splitParam.slice(1).join("=");
	}
	if(url === "/getVideo" && req.method === "GET" && Object.keys(params).indexOf("id") >= 0){
		if(ytstream.validateID(params['id'])){
			ytstream.stream(ytstream.getURL(params['id']), {
				type: 'audio',
				quality: 'highest'
			}).then(stream => {
				console.log(stream.stream);
				stream.stream.pipe(res);
			}).catch(err => {
				res.end();
			});
		} else {
			res.end();
		}
	} else {
		res.end();
	}
});

server.listen(80);
```
In the example above, a new endpoint is created named `/getVideo`. When you make a `GET` request to this endpoint with the parameter `id` provided, it automatically generates a new audio which can be used for a HTML audio tag as HTML audio tags by default create a `GET` request to the source thas has been set. So with this example, you could use this for your HTML page:
```html
<!DOCTYPE html>
<html>
	<head>
		<title>Some title</title>
	</head>
	<body>
		<audio src="/getVideo?id=dQw4w9WgXcQ" controls></audio>
	</body>
</html>
```
This example will create an audio element of the YouTube video with the id `dQw4w9WgXcQ`.

**Comment by AhsanSarwar45** [comment]
Thanks for the detailed response! I got it to work! But it appears that the audio is not seekable. Is that possible?

**Comment by Luuk-Dev** [comment]
That is indeed possible. This is caused because the server is downloading the data while the client is playing the audio. When the client tries to seek, the server doesn't have the data for that specific part yet. This makes the audio not seekable.
