### ISSUE TITLE
IP rotation

### ISSUE THREAD

**Issue by retrouser955** [Luuk-Dev/YT-Stream#13]
Is there a method to implement IP rotation using yt-stream like [here](https://www.npmjs.com/package/@distube/ytdl-core#ip-rotation)

**Comment by Luuk-Dev** [comment]
Hey retrouser955! Sorry for my late response. I was busy with my final school exams. There is as of now not a method to implement this. I will add this as a feature in the next version.

**Comment by Luuk-Dev** [comment]
I have just released an update which allows you to use a custom agent. Inside this custom agent, you can change the `localAddress`  for requests. Make sure that you use a local address which is available inside your network interfaces.

**Comment by retrouser955** [comment]
> I have just released an update which allows you to use a custom agent. Inside this custom agent, you can change the `localAddress` for requests. Make sure that you use a local address which is available inside your network interfaces.

Thank you ❤️
