### ISSUE TITLE
Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by framilano** [Luuk-Dev/YT-Stream#16]
Hi, something weird is happening, the result of `ytstream.stream` returns this error:

**Sign in to confirm you’re not a bot**

But only while using my ubuntu aws EC2 instance, from my Windows desktop everything works fine, but it doesn't make any sense at all.

**Comment by Luuk-Dev** [comment]
YouTube has a bot detection system for the youtubei api as well. It has probably detected that your server's IP is a server IP and not an ISP IP like your Windows desktop is. Therefore it blocks requests made from your server and not made from your Windows desktop. You could try using a proxy which hasn't been flagged by YouTube as a server, but it would probably be hard to find one.
