### ISSUE TITLE
Duration is in ms not seconds

### ISSUE THREAD

**Issue by elektracodes** [Luuk-Dev/YT-Stream#3]
Is this the intended behavior? Because in the doc, you say that the duration should be in seconds

**Comment by Luuk-Dev** [comment]
Hey there 👋

In previous versions it was seconds indeed, but I forgot to update it in the docs. I changed it as it made it easier to use timestamps with it and as most packages also use miliseconds instead of seconds. Thanks for noticing, I'll update the docs.
