### ISSUE TITLE
BUG: You cannot retrieve the duration from restricted videos

### ISSUE THREAD

**Issue by elektracodes** [Luuk-Dev/YT-Stream#4]
e.g. https://www.youtube.com/watch?v=4lzqUe1Qfec 

Can I PR this case?

**Comment by Luuk-Dev** [comment]
As age restricted video's don't provide any data, you are only able to get the data of these video's by setting a cookie of an account that **has** confirmed their age. You can set this cookie by changing the `cookie` property to the cookie of the account.
