### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by retrouser955** [Luuk-Dev/YT-Stream#9]
When I download, it throws an error saying `TypeError: Cannot read properties of undefined (reading 'userAgent')`.

Turns out, when the `ytStream` object is null, you need to add a guard to it. Replacing `typeof ytstream.userAgent` on line 39, info.js with `typeof ytstream?.userAgent` seems to do the trick. Line 46 of the same file seem to have the same issue as well and is quickly resolved using the same method!

**Comment by retrouser955** [comment]
Oh sorry I didn't take a screenshot of the error stack but I will try to submit a pull request!

**Comment by retrouser955** [comment]
Please check #10

**Comment by Luuk-Dev** [comment]
Can you provide me the code you used so I can try to recreate the error?
